apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-mgmt-config
  namespace: kube-system
data:
  PAN_SERVICE_NAME: pan-mgmt-svc
  PAN_MGMT_SECRET: pan-mgmt-secret

  # Panorama settings
  PAN_PANORAMA_IP: {{ .Values.panorama.ip | quote }}
  {{- if .Values.panorama.ip2 }}
  PAN_PANORAMA_IP2: {{ .Values.panorama.ip2 | quote }}
  {{- end }}
  PAN_DEVICE_GROUP: "dev-dg"
  PAN_TEMPLATE_STACK: "k8s-stack"
  PAN_CGNAME: "Panorama"

  # Intended License Bundle type - "CN-X-BASIC, CN-X-BND1, CN-X-BND2"
  {{- if eq .Values.firewall.licenseBundle "basic" }}
  PAN_BUNDLE_TYPE: "CN-X-BASIC"
  {{- else if eq .Values.firewall.licenseBundle "bundle1" }}
  PAN_BUNDLE_TYPE: "CN-X-BND1"
  {{- else if eq .Values.firewall.licenseBundle "bundle2" }}
  PAN_BUNDLE_TYPE: "CN-X-BND2"
  {{- end }}

  # Non-mandatory parameters
  # Recommended to have same name as the cluster name provided in Panorama Kubernetes plugin - helps with easier identification of pods if managing multiple clusters with same Panorama
  #CLUSTER_NAME: "<Cluster name>"
  #PAN_PANORAMA_IP2: ""

  # Comment out to use CERTs otherwise bypass encrypted connection to etcd in pan-mgmt.
  # Not using CERTs for etcd due to EKS bug
  {{- if or (eq .Values.cluster.deployTo "eks") (eq .Values.cluster.deployTo "openshift") }}
  ETCD_CERT_BYPASS: ""          # No value needed
  {{- else }}
  #ETCD_CERT_BYPASS: ""          # No value needed
  {{- end }}

  # Comment out to use CERTs otherwise PSK for IPSec between pan-mgmt and pan-ngfw
  {{- if eq .Values.cluster.deployTo "openshift" }}
  IPSEC_CERT_BYPASS: ""         # No values needed
  {{- else }}
  #IPSEC_CERT_BYPASS: ""         # No values needed
  {{- end }}
